### ISSUE TITLE
Building deb packages using docker

### ISSUE THREAD

**Issue by kakoni** [vrk-kpa/xroad-public#1]
Hi! 
So would it make sense to also dockerize the build process for deb packages?

**Comment by iluwatar** [comment]
The `Dockerfile` to build deb packages will be included in the next release that is coming out during the following few days.

**Comment by pe3** [comment]
It would be really cool to have `docker-compose.yml` based stand alone example setting up servers for running [x-road-adapter-example](https://github.com/petkivim/x-road-adapter-example).

**Comment by pe3** [comment]
The installation instructions advice to edit `hosts/example_xroad_hosts.txt`.  The content of the file is:
```
[cs-servers]
cs1.mydomain.com ansible_ssh_user=ubuntu
cs2.mydomain.com ansible_ssh_user=ubuntu

[ss-servers]
ss1.mydomain.com ansible_ssh_user=ubuntu
ss2.mydomain.com ansible_ssh_user=ubuntu
rh1.mydomain.com ansible_ssh_user=ec2-user
rh2.mydomain.com ansible_ssh_user=ec2-user

[cp-servers]
cp.mydomain.com ansible_ssh_user=ubuntu

[example:children]
cs-servers
ss-servers
cp-servers
```

What are these?

**Comment by pe3** [comment]
Here is an [Oracle Java 8 Dockerfile](https://github.com/dockerfile/java/blob/master/oracle-java8/Dockerfile) to start with.

**Comment by skallio** [comment]
The original issue is about building deb packages using docker and that is now available and published. The continuation is asking about running X-Road servers under docker, which I address here.

There is no docker setup X-Road environment for the reasons I try to explain below:

X-Road infrastructure consists of multiple servers, for example, central server, configuration proxy, security server and information system, most of which include multiple services. 

Security server alone is a combination of several service processes like proxy, signer, monitor and infrastructure services like postgresql and jetty. The combination is installed using the operating system packaging (deb or rpm) and is controlled through the init system offered by the operating system, systemd on RedHat and upstart on Ubuntu 14.

The purpose of Docker containers is to run a single process inside a container, not a combination of several processes. With docker compose or a similar mechanism, it is possible to build a combination of processes that communicate with each other. However, in case of an X-Road server, like security server, it would mean to break down the current setup completely, open the packaging and create a new for docker. Currently there are no plans to do that and we are not convinced that it would be a wise thing to do.

For more information on X-Road architecture, please check the documentation at https://github.com/vrk-kpa/xroad-public/tree/master/src/doc.

For an easy development environment setup, it is possible to run X-Road servers using lxd on Ubuntu. Unlike docker, lxd offers a full operating system environment including init system. The setup of a security server can be done using Ansible by modifying the host file. Assuming you have created an lxd container named my-security-server, create a the host file named lxd_hosts.txt:

[ss-servers]                                                                                                                
my-security-server ansible_connection=lxd    

and go to xroad-public/ansible and run:

ansible-playbook -i hosts/lxd_hosts.txt palveluvayla_init.yml

**Comment by hanhaka** [comment]
Issue resolved, closing it.
