### ISSUE TITLE
Possible infinite loop in ee.ria.xroad.asyncdb.messagequeue.MessageQueueImpl

### ISSUE THREAD

**Issue by erikjogi** [vrk-kpa/xroad-public#10]
MessageQueueImpl.createTempDir() has a while() loop that will run infinitely if creating of the directory fails. It can be caused easily by insufficient permissions or some other disk-level error.

Also it is very rarely a good idea to catch all exceptions with catch(Exception). In this case a try/catch loop in absolutely pointless because by documentation the new File() and mkdirs() can only fail with a NullPointerException or a SecurityException. Both cases will never resolve itself and therefore doing it in loop has no effect. Catching NullPointerException is never a good idea - even outside the loop - it is a programming error and cannot be fixed in a catch block.

**Comment by iluwatar** [comment]
I agree with your comments, this method has smells. The code in question is part of legacy asyncdb implementation that is unused. In fact the whole asyncdb will be removed in the next major release.

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
