### ISSUE TITLE
Put documentation in ODT/PDF

### ISSUE THREAD

**Issue by EmidioStani** [vrk-kpa/xroad-public#11]
Hello,

I believe it could be better if you put the documentation (/src/doc) in ODT or PDF format in addition/alternative to DOCX.

Thanks, it looks an interesting project !

**Comment by iluwatar** [comment]
We are in the process of migrating the documentation in `src/doc` to markdown format. Would this be suitable for you?

**Comment by EmidioStani** [comment]
Yes sure

**Comment by hanhaka** [comment]
Markdown (MD) format will be the recommended format in the future.
Current documentation will be converted to MD format one by one.

Issue resolved, closing it.
