### ISSUE TITLE
Can't install xroad-centralserver

### ISSUE THREAD

**Issue by nilpoint** [vrk-kpa/xroad-public#12]
Hello,

I met a proplem when I install the xroad-centralserver with the command:

` sudo apt-get install xroad-centralserver`

the terminal output is:

```
E: Failed to fetch http://x-road.eu/packages/pool/main/x/xroad/xroad-center_6.8.6.20161020095957_all.deb  403  Forbidden

E: Failed to fetch http://x-road.eu/packages/pool/main/x/xroad/xroad-centralserver_6.8.6.20161020095957_all.deb  403  Forbidden
```

I've browsed the [repo url](http://x-road.eu/packages/pool/main/x/xroad/), and found those two packages don't exit now.

Please support. Thank you.

**Comment by iluwatar** [comment]
@nilpoint you are right, there was a .htaccess restriction preventing access to the packages. It should be fixed now. Can you please try again?

**Comment by nilpoint** [comment]
@iluwatar yes, it worked. Thank you for quick support.
