### ISSUE TITLE
create Certificate error

### ISSUE THREAD

**Issue by rock1103** [vrk-kpa/xroad-public#13]
hello:
I use keytool,try to create Internal TLS Certificate,client Certificate,key Certificate,and import to xroad security server,it report error,Do you have some tools to create Certificate correctlly.
thank you.

**Comment by iluwatar** [comment]
@rock1103 can you elaborate what you are trying to achieve? What steps have you done and what error do you get?

**Comment by rock1103** [comment]
Hi:
I enter the key and certificate module of back-stage management, generated key and csr,and use the csr,and code is
 openssl req  -key sign_csr_membertest001.pem -new -x509 -days 7300 -sha256 -out cert.pem

an error occur: unable to load Private Key
140192030459552:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: ANY PRIVATE KEY

**Comment by iluwatar** [comment]
In the command `openssl req -key sign_csr_membertest001.pem -new -x509 -days 7300 -sha256 -out cert.pem` what you are giving as key parameter looks like certificate request.

**Comment by rock1103** [comment]
openssl req -in $1 -inform DER -out csr/${SER}.csr
openssl ca -config CA.cnf -extensions $EXT -days 7300 -notext -md sha256 -in csr/${SER}.csr
the command in the shell code
what the $1,$EXT means, now I want to create sign and auth certificate, should I use these two command to create it?

**Comment by iluwatar** [comment]
The certificate requests can be created and downloaded in the security server user interface. The requests can then be signed with the Test-CA system found at https://github.com/vrk-kpa/xroad-public/tree/master/utils/testca. I'm not sure why you are trying to create certificate requests and sign them manually?

**Comment by rock1103** [comment]
I test use Test-CA with some error,So I read the code,and in the code with two command
openssl req -in $1 -inform DER -out csr/${SER}.csr
openssl ca -config CA.cnf -extensions $EXT -days 7300 -notext -md sha256 -in csr/${SER}.csr
I want to try it

**Comment by rock1103** [comment]
and I use these command in Test-CA:
ca@server1:/usr/local/bin$ sign /home/rock/sign_csr_20161221_member_test_TEST1_membertest001.pem >/home/rock/signtest.pem
unable to load X509 request
139859045906080:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1338:
139859045906080:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:390:Type=X509_REQ

**Comment by iluwatar** [comment]
Looks like the certificate request is in wrong format. The Test-CA expects DER format and in this case you are feeding it PEM.

**Comment by rock1103** [comment]
Hi: 
I have use DER and here is command:
ca@server1:/usr/local/bin$ sign /home/rock/sign_csr_20161222_member_test_TEST1_membertest001.der >/home/rock/signtest.pem
Using configuration from CA.cnf
Check that the request matches the signature
Signature ok
The countryName field needed to be supplied and was missing

**Comment by rock1103** [comment]
and I have also , run init.sh under /home/ca/CA, with some error:
1 out of 1 certificate requests certified, commit? [y/n]y
Write out database with 1 new entries
Data Base Updated
Generating TSA Certificate
Generating RSA private key, 4096 bit long modulus
..............................................++
........++
unable to write 'random state'
e is 65537 (0x10001)
writing RSA key

**Comment by iluwatar** [comment]
> The countryName field needed to be supplied and was missing

The instructions for creating the certificate requests are country (and sometimes version) specific. For Finland there are good step-by-step instructions starting from here https://confluence.csc.fi/display/Palveluvayla/Harjoitus+osa+1+-+ohjelmiston+asennus. Unfortunately the documents are in Finnish but hopefully you can use browser's translate to English functionality to understand it a bit better. Also, I recommend that you build the software packages from the source code by yourself since the ones that come from the x-road.eu repository are different and the instructions don't directly apply to them.

**Comment by iluwatar** [comment]
> unable to write 'random state'

I haven't encountered this before but please see if this helps: 
http://stackoverflow.com/questions/94445/using-openssl-what-does-unable-to-write-random-state-mean

**Comment by rock1103** [comment]
now I step by  https://github.com/vrk-kpa/xroad-public/tree/master/utils/testca,
and 
ca@server1:/usr/local/bin$ sign /home/rock/sign_csr_20161222_member_test_TEST1_membertest001.der >/home/rock/signtest.pem
csr/02.csr: Permission denied
140378813650592:error:0200100D:system library:fopen:Permission denied:bss_file.c:398:fopen('csr/02.csr','w')
140378813650592:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:

but vi /etc/sudoers
# User privilege specification
root    ALL=(ALL:ALL) ALL
ca      ALL=(ALL:ALL) ALL
ca also have the root Permission

**Comment by iluwatar** [comment]
Something wrong with file/directory access rights. Can you check that your Test-CA permissions look something like this:

`/home/ca/CA   drwxrwxr-x   ca ca`
`/home/ca/CA/csr drwxr-xr-x   ca ca`
`/home/ca/CA/csr/02.csr -rw-r--r--   ca ca`

**Comment by rock1103** [comment]
ca@server1:/usr/local/bin$ sign /home/rock/sign_csr_20161222_member_test_TEST1_membertest001.der >/home/rock/signtest.pem
Using configuration from CA.cnf
Check that the request matches the signature
Signature ok
The countryName field needed to be supplied and was missing
also have countryName missing issue
now I install x-road from x-road.eu/packages of install document ,  should I build the software packages from the source code by myself?   x-road.eu/packages not solve these problem?

**Comment by iluwatar** [comment]
The source code and documentation in this repository is for version 6.7.13 (the current Finnish version) whereas the software in x-road.eu/packages is 6.8.6 (the current Estonian version). To use the version 6.7.13 you can either build the packages from the source code or configure a package repository which has this version. With 6.7.13 you can mostly follow the instructions at https://confluence.csc.fi/display/Palveluvayla/Harjoitus+osa+1+-+ohjelmiston+asennus except that you need to sign the certificate requests yourself.

**Comment by rock1103** [comment]
Hi:
x-road.eu/packages is 6.8.6 (the current Estonian version),this source code is open in github?

**Comment by rock1103** [comment]
if I use version 6.7.13 (the current Finnish version) , can I install security server and center server of xroad whole technology platform?

**Comment by iluwatar** [comment]
The source code for 6.8.6 is not yet available. The 6.7.13 version includes the whole platform i.e. central server, security server etc.

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
