### ISSUE TITLE
MANAGING THE APPROVED CERTIFICATION SERVICES

### ISSUE THREAD

**Issue by huangsongyun** [vrk-kpa/xroad-public#17]
Hi,
Could you do me a favor ?
One part of  **11.1.ADDING AN APPROVED CERTIFICATION SERVICE** in  UG-CS doc as below:
_**2.	Locate the certification service CA certificate file and click Next.**_
in step 2 ,how or where can I get the **certification service CA certificate file** ? 
Details as attached.
![Uploading file.png…]()

**Comment by iluwatar** [comment]
As in https://github.com/vrk-kpa/xroad-public/issues/16 it depends on the CA being used. If you are using the OpenSSL based CA for testing purposes described here https://github.com/vrk-kpa/xroad-public/tree/master/utils/testca you can find the certificates from the server's `/home/ca/CA/certs` folder.

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
