### ISSUE TITLE
How to implement subsystems registration ?

### ISSUE THREAD

**Issue by 729234500** [vrk-kpa/xroad-public#19]
How to implement subsystems registration ?

**Comment by iluwatar** [comment]
Given that
- Central server is configured and working
- Management services have been configured and working
- The security server where the subsystem will be registered has valid authentication and signing certificates

When these conditions are met the process usually goes as follows.

1. The subsystem is added on the central server
2. The subsystem is added on the security server
3. The management request for adding the new subsystem is approved

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
