### ISSUE TITLE
Travis-CI integration / Pull requests

### ISSUE THREAD

**Issue by kakoni** [vrk-kpa/xroad-public#2]
Since this now open-source, it probably would make sense to plug this into travis-ci?

**Comment by petkivim** [comment]
This is a snapshot repository and it'll be updated every two weeks, after each sprint. In our daily development we're currently using Jenkins as our CI tool.

**Comment by kakoni** [comment]
Ok. So what happens if something is commited/pull-requested into this github repo?

**Comment by pkivima** [comment]
We review the pull request and decide on approval or rejection. If the pull request is approved, the changes are merged to our development repository. The changes are published in the public repository when the next version after the merge is released.

**Comment by kakoni** [comment]
Cool, thanks. Last question; any specific reasons why development repo is separate from this github?

**Comment by petkivim** [comment]
The development repo contains all the components of X-Road (security server, central server, configuration proxy) in the same repository, but the public repo contains the security server only. At a later stage, when all the components are public, the development repo could be public as well.

**Comment by kakoni** [comment]
Aah, ok, make sense. Closing this.
