### ISSUE TITLE
Give me a real information system example

### ISSUE THREAD

**Issue by 729234500** [vrk-kpa/xroad-public#20]
@petkivim @thanhiro @iluwatar 
Please give me a real example and it can be connected to the information system security server.
Thank you

**Comment by petkivim** [comment]
You can use the X-Road Adapter Example for testing how adding a new service works. Just deploy the test service and then follow the instructions of the Security Server User Manual chapter 6 X-Road Services.

X-Road Adapter Example
https://github.com/petkivim/x-road-adapter-example

Security Server User Manual
https://github.com/vrk-kpa/xroad-public/blob/master/src/doc/Manuals/ug-ss_x-road_6_security_server_user_guide_2.7_Y-883-32.docx?raw=true

Thanks,
Petteri

**Comment by 729234500** [comment]
@petkivim 
Thanks,  
I see   X-Road Adapter Example  no client.

I DON'T KNOW HOW TO DO IT.

**Comment by petkivim** [comment]
Please check out this example:

https://github.com/petkivim/x-road-test-client

You might find this library useful as well:

https://github.com/petkivim/xrd4j

Br,
Petteri

**Comment by 729234500** [comment]
@petkivim 
We succeeded in building a central server and the security server and use it is testing.
Therefore, we need a real example test the security server and a central server.I hope it can be established in a real environment, rather than a test validation information system cannot,and we want to know what a real information system is a way.
So i hope give me a real open resources information system instead of a simple example.
Thanks

**Comment by 729234500** [comment]
@petkivim 
Sends a string = "HelloWorld"
Returns an answer "Yes". 
It must be established in a real environment. 
thanks.
It's eaziliy for you

**Comment by petkivim** [comment]
If you want to test X-Road with a real production level information system you have three options:

1) Use your own information system and integrate it to you own X-Road instance
2) Use some open API available in the internet and integrate to your own X-Road instance
3) Join Finnish Palveluväylä (NB! only for Finnish organizations) or Estonian X-tee (NB! only for Estonian organizations) and make a service agreement with a service provider, and start using their service.

**Comment by 729234500** [comment]
@petkivim 
 I am never written like xroad information system as an example .

Can you give me your test case

**Comment by petkivim** [comment]
Unfortunately our automated test cases are not public yet. However, you can material about X-Road performance testing here:

https://github.com/vrk-kpa/xroad-load-tests

X-Road E2E monitoring tool:

https://github.com/vrk-kpa/xroad-e2e-client

**Comment by 729234500** [comment]
@petkivim 
oh regrettable！
Also thank you

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
