### ISSUE TITLE
Gem::LoadError rake 11.2.2

### ISSUE THREAD

**Issue by fanxingguang** [vrk-kpa/xroad-public#21]
Hello,We recently are used X-road. We have a problem when we compile and construct the engineering. We can find we have installed rake 11.2.2 when we run the "update_ruby_dependencies.sh". Then the process was stop and gave a message "Gem::LoadError: You have already activated rake 11.3.0, but your Gemfile requires rake 11.2.2. Prepending `bundle exec` to your command may solve this".We are looking foward your response.

**Comment by iluwatar** [comment]
Have you read https://github.com/vrk-kpa/xroad-public/blob/master/README.md section "Getting started"? On a clean build machine the steps mentioned in the document should work. If your build machine is not clean and has some Ruby stuff already installed you may get version related errors.

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
