### ISSUE TITLE
How many number of maximum response in the test - service side?

### ISSUE THREAD

**Issue by 729234500** [vrk-kpa/xroad-public#22]
How many number of maximum response in the test - service side?
I test it only 200！！
I dont know what happened it

**Comment by iluwatar** [comment]
I'm not sure what you are asking. What kind of test setup do you have?

**Comment by 729234500** [comment]
https://github.com/petkivim/x-road-test-service
and
https://github.com/petkivim/x-road-test-client
Thanks

**Comment by pkivima** [comment]
The Test Service does not have any limit for for the number of requests. If you're using the Test Client the number of the requests sent by the client is defined in ``` src /main/resources /settings.properties``` file.

https://github.com/petkivim/x-road-test-client/blob/master/src/src/main/resources/settings.properties

The properties are explained in the documentation. Please take a look at

https://github.com/petkivim/x-road-test-client

**Comment by 729234500** [comment]
ok Thanks  I know.
At the same time concurrent requests the largest number is 200?

# Security server URL/IP
proxy.url=http://x.x.x.x/
# Number of thread executors
thread.executor.count=300
# Number of threads
thread.count=300
# Thread sleep time in milliseconds between requests
thread.sleep=200
# Number of requests per thread
thread.request.count=1
# Maximum time in milliseconds that a single thread runs
thread.request.maxtime=0

This is my modified parameter list

**Comment by petkivim** [comment]
The Test Client doesn't set any limit for the number of concurrent threads. You could try to raise the maximum heap size and see if it helps.

```java -jar -Xmx512m x-road-test-client-0.0.4.jar```

**Comment by 729234500** [comment]
@petkivim  Why the Test Service response only 200? the rest of the wait

**Comment by petkivim** [comment]
In the code there's no maximum limit for the Test Service. Probably the service just isn't able to handle more concurrent requests, because it has reached its limit. You can try to increase the number of concurrent requests increasing the maximum heap size of the Test Service, but I'm not sure if it will help. Increasing the number of concurrent requests might require refactoring the implementation.

**Comment by 729234500** [comment]
@pkivima  OK thanks

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
