### ISSUE TITLE
Cannot locate configuration source /etc/xroad/conf.d/proxy.ini

### ISSUE THREAD

**Issue by paundo** [vrk-kpa/xroad-public#24]
I'm configuring a central server. The error message in the /var/log/xroad/signer.log is:
e.r.x.common.SystemPropertiesLoader - Error while loading /etc/xroad/conf.d/proxy.ini: {}
org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source /etc/xroad/conf.d/proxy.ini
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:259) ~[signer-1.0.jar:na]
	at 
...

**Comment by iluwatar** [comment]
This error message is printed to central server's signer.log on signer startup. However, it is harmless. The mentioned proxy configuration file exists only on security servers.

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
