### ISSUE TITLE
SEND DATA TO 224.0.0.251?

### ISSUE THREAD

**Issue by 729234500** [vrk-kpa/xroad-public#26]
@petkivim @iluwatar 
After testing, the system will continue to issue a request to 224.0.0.251. And the response time will be very long. Can you tell me why?
THANKS

**Comment by iluwatar** [comment]
Is there a service responding at 224.0.0.251? The service address can be configured in the provider security server's user interface.

**Comment by 729234500** [comment]
No，I have not configured anything about 224.0.0.251.

**Comment by iluwatar** [comment]
What component in your test system is making requests to the IP address? Is it the test client, security server, central server or the test service? Do you detect this from the logs or via some other means?

**Comment by 729234500** [comment]
Provider secerity server

**Comment by 729234500** [comment]
Use wireshark software for viewing

**Comment by iluwatar** [comment]
In addition to communicating with backend services and other security servers the security server makes OCSP requests to certfication services and timestamping requests to the timestamper URL. The certification and timestamping services are defined on the central server. Maybe the request you see is related to either one of these?

**Comment by 729234500** [comment]
Maybe...I can try it. Wait me a moment 
THANKS......

**Comment by 729234500** [comment]
@iluwatar 
This ip address you can search in Google.
224.0.0.251 can not be configured as a reserved address. So, I think it should not ocsp or timestamp ip address.

**Comment by olli-lindgren** [comment]
Is it multicast DNS https://www.wikiwand.com/en/Multicast_DNS ? It's not necessarily related to the security server at all. There are probably guides for your platform to check for and/or disable multicast DNS if you want to.

**Comment by 729234500** [comment]
@olli-lindgren  @iluwatar 
This is a list of all services
I didn't found any one about multicast DNS service. 

mountnfs-bootclean.sh start/running
rsyslog start/running, process 779
tty4 start/running, process 850
udev start/running, process 296
upstart-udev-bridge start/running, process 291
mountall-net stop/waiting
passwd stop/waiting
rc stop/waiting
startpar-bridge stop/waiting
ureadahead-other stop/waiting
apport start/running
systemd-logind start/running, process 972
tty5 start/running, process 853
xroad-jetty start/running, process 904
console-setup stop/waiting
hwclock-save stop/waiting
irqbalance stop/waiting
plymouth-log stop/waiting
mountall.sh start/running
failsafe stop/waiting
atd start/running, process 989
dbus start/running, process 799
resolvconf start/running
ssh start/running, process 905
mounted-var stop/waiting
plymouth-shutdown stop/waiting
plymouth stop/waiting
udev-fallback-graphics stop/waiting
checkroot.sh start/running
xroad-confclient start/running, process 906
control-alt-delete stop/waiting
hwclock stop/waiting
mounted-proc stop/waiting
xroad-signer start/running, process 907
setvtrgb stop/waiting
shutdown stop/waiting
cron start/running, process 988
mountkernfs.sh start/running
xroad-monitor start/running, process 908
mountall stop/waiting
mounted-debugfs stop/waiting
console stop/waiting
mounted-run stop/waiting
acpid start/running, process 909
checkfs.sh start/running
checkroot-bootclean.sh start/running
mountnfs.sh start/running
nginx start/running, process 978
ufw start/running
kmod stop/waiting
plymouth-stop stop/waiting
rcS stop/waiting
wait-for-state stop/waiting
bootmisc.sh start/running
flush-early-job-log stop/waiting
friendly-recovery stop/waiting
rc-sysinit stop/waiting
upstart-socket-bridge start/running, process 479
mountdevsubfs.sh start/running
tty2 start/running, process 863
upstart-file-bridge start/running, process 717
udevtrigger stop/waiting
mtab.sh start/running
tty3 start/running, process 864
container-detect stop/waiting
mounted-dev stop/waiting
udev-finish stop/waiting
hostname stop/waiting
mountall-reboot stop/waiting
network-interface (lo) start/running
network-interface (eth0) start/running
network-interface (eth1) start/running
tty1 start/running, process 1521
xroad-proxy start/running, process 910
mountall-shell stop/waiting
mounted-tmp stop/waiting
plymouth-ready stop/waiting
plymouth-splash stop/waiting
plymouth-upstart-bridge stop/waiting
udevmonitor stop/waiting
mountall-bootclean.sh start/running
network-interface-security (network-interface/eth1) start/running
network-interface-security (network-interface/eth0) start/running
network-interface-security (network-interface/lo) start/running
network-interface-security (networking) start/running
networking start/running
tty6 start/running, process 867
dmesg stop/waiting
procps stop/waiting
console-font stop/waiting
network-interface-container stop/waiting
ureadahead stop/waiting

**Comment by 729234500** [comment]
Maybe you can find it . thanks

**Comment by olli-lindgren** [comment]
As far as I know, Avahi is the daemon on linux platforms for mDNS but I don't see it listed in the above services. I don't know what is causing the traffic on your server.

Linux platform support is out of the scope of our team. X-Road doesn't have any direct mDNS capabilites, it just uses network support from the OS. If you don't want mDNS traffic on your environment, you should find what is causing it in your system.

If you can show us that it is definitely one of the X-Road services that is sending data to the IP you mentioned we should be able to continue the investigation on our end.

**Comment by 729234500** [comment]
@olli-lindgren  OK ，Has proven to be our problem.In the absence of open services, will still send data to 224.0.0.255. Although do not know why.

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
