### ISSUE TITLE
Sending subsystem registration request fails

### ISSUE THREAD

**Issue by rajotico** [vrk-kpa/xroad-public#27]
So far I have been able to register a security server on the central Server, next I am trying to create a subsystem,  but when I try sending the client registration request I get this error on a red bar:
Failed to send registration request: Unknown service: SERVICE:FI/GOB/10001/clientReg

the jetty.log file sys:
 INFO  / - Server.ServerProxy.UnknownService: Unknown service: SERVICE:FI/GOB/10001/clientReg
	at ee.ria.xroad.common.CodedException.fromFault(ee/ria/xroad/common/CodedException.java:139)

I am able to create the same  Registration Request on the Central server Server and is currently listed with status 'WAITING', According to the docs the request from the security server needs to arrive to able to approve it..
I am following the tutorial at https://confluence.csc.fi/pages/viewpage.action?pageId=64971830, but there's no steps for the central server, only for the security server.

**Comment by iluwatar** [comment]
> So far I have been able to register a security server on the central Server, next I am trying to create a subsystem, but when I try sending the client registration request I get this error on a red bar:
Failed to send registration request: Unknown service: SERVICE:FI/GOB/10001/clientReg

Registering subsystem uses so called management services and probably these have not been configured yet. To do it, follow these general steps: 
1. You need to designate one of the security servers to provide management services for the X-Road instance.
2. On the central server's System Settings page you find WSDL address and Services address for the management services
3. On the security server add new service to the member and use the addresses found in the previous step. Also add access rights to these services.
4. Try again the subsystem registration on the security server that errored.
5. When you are able to register new subsystems you should also move the management services to a subsystem. In the future versions the services attached directly to members will not work anymore.

> the jetty.log file sys:
INFO / - Server.ServerProxy.UnknownService: Unknown service: SERVICE:FI/GOB/10001/clientReg
at ee.ria.xroad.common.CodedException.fromFault(ee/ria/xroad/common/CodedException.java:139)

Currenty it is looking for the client registration service from FI/GOB/10001 member but it is not available.

> I am able to create the same Registration Request on the Central server Server and is currently listed with status 'WAITING', According to the docs the request from the security server needs to arrive to able to approve it..

Yes, the subsystem registration needs to be done on both the central server and the security server. After that the management request on the central server can be approved.

> I am following the tutorial at https://confluence.csc.fi/pages/viewpage.action?pageId=64971830, but there's no steps for the central server, only for the security server.

Currently the documentation for configuring the central server is hardly sufficient. We are working to improve this soon.

**Comment by rajotico** [comment]
Thanks, that makes sense, I only have one security server instance which is already designated to provide management.  I was able to add the WSDL to it, which created three services on the security server, and gave access to the security-server-owners group. 

However connection continues to fail, the error now says:
 Connect to [mycentralserver]:4400 [mycentralserver/10.0.0.101] failed: Connection refused (Connection refused)

I checked on the central server and port 4400 is not available, but there no errors reported on the logs...

**Comment by iluwatar** [comment]
Try to change the management services address from http://<server>:4400 to https://<server>:4001. That should be available.

**Comment by rajotico** [comment]
I get:
{"messages":[["error",["Failed to send registration request: Client 'MEMBER:FI/GOB/10001' has no IS certificates"]]],"data":{"stderr":null}}

No errors on the central server.
