### ISSUE TITLE
Development for pure RESTful services

### ISSUE THREAD

**Issue by eramirez-sv** [vrk-kpa/xroad-public#28]
I understand there is a xroad-rest-gateway which translates SOAP to REST and viceversa, this works but I would rather not have so many parts to the solution. The Xroad Security server only allows adding SOAP/WSDL services. These days everything is based on REST APIs which are simpler to develop. It use to be that SOAP offered more structure and control but  now is possible to define and validate REST service schemas:  http://json-schema.org/implementations.html   
 And to sign REST messages: https://jwt.io/ 

Are there any plans to move xroad protocol from SOAP to REST altogether? I think this would be a slimmer and more accesible solution.

**Comment by hanhaka** [comment]
Thanks for your comment. This is something that has been seriously considered every now and then. We have also seen that moving xroad protocol from SOAP to REST would be a proper way to upgrade xroad to the next, modern level. However, there are currently no actual steps agreed for doing this: it would require a big implementation effort to make a such development work and at the moment it is not unfortunately possible.

What we are planning to do (and the work has actually already initiated), is that the xroad-rest-gateway component is further developed and integrated as a part of default xroad installation package. By doing this we are helping xroad to support REST, if not fully but at least better than it currently supports.

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
