### ISSUE TITLE
adding translation

### ISSUE THREAD

**Issue by eramirez-sv** [vrk-kpa/xroad-public#29]
I have create a Spanish version of the UI files (*_es.yml). Can these be added to the repository, should I submit a pull request?
Thanks!

**Comment by hanhaka** [comment]
Thanks for your implementation work for developing Spanish UI! It is really great to see there are devoted developers working for the better X-Road.

Unfortunately we can only support English UI. This decision is made by X-Road Steering Group. To support multi-language UI would require continuous development/update work to keep the UI & UI texts up-to-date when changing, renewing and updating the UI. We want to keep things simple and make sure the UI is always up-to-date and it's easy to make changes for it.

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
