### ISSUE TITLE
setting up monitoring

### ISSUE THREAD

**Issue by eramirez-sv** [vrk-kpa/xroad-public#30]
The docs (Monitoring-architecture.md) mention environmental monitoring, how can I set up operational monitoring?
Also the doc explains how to pull messages, how are they consumed? is there a monitoring UI somewhere?

Thanks,

**Comment by iluwatar** [comment]
The setup is described in ig-ss (security server installation guide) chapter 2.8. After the installation monitoring data can be queried from the monitoring server with the request message described in Monitoring-architecture.md or via JMX protocol. At the moment there is no separate monitoring UI but connecting to monitoring JMX interface with something like Nagios or Zabbix should provide this.

**Comment by hanhaka** [comment]
Issue has been solved or no feedback from requester has been received.
