### ISSUE TITLE
Unable to locate package xroad-monitor

### ISSUE THREAD

**Issue by rock1103** [vrk-kpa/xroad-public#7]
Hi:
I install the xroad with ig-ss_x-road_v6_security_server_installation_guide_2.2.1_Y-745-8.doc,
when I install xroad security server with this code "sudo apt-get install xroad-securityserver",
then
```
tt@server:~$ sudo initctl list | grep "^xroad-"
xroad-jetty start/running, process 1186
xroad-confclient start/running, process 1198
xroad-signer start/running, process 1199
xroad-proxy start/running, process 1200
```
it is Ok
but ,when I install xroad-monitor,it has a error,

```
tt@server:~$ sudo apt-get install xroad-monitor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package xroad-monitor
```
can you help me to solve this problem,thank you.

**Comment by iluwatar** [comment]
Unfortunately the package is not available in the repository indicated by the installation guide. To install monitoring support you need to add another repository:

```
sudo apt-add-repository -y "deb http://www.nic.funet.fi/pub/csc/x-road/client/ubuntu-dev-current/packages stable main"
curl http://www.nic.funet.fi/pub/csc/x-road/client/ubuntu-dev-current/packages/dists/stable/palveluvayla@gofore.com.asc | sudo apt-key add -
```

After adding the repository proceed with commands `apt-get update` and `apt-get install xroad-monitor`.

**Comment by rock1103** [comment]
thank you, it works
