### ISSUE TITLE
Client not found in global configuration

### ISSUE THREAD

**Issue by rock1103** [vrk-kpa/xroad-public#8]
Hi:
I have installed x-road with the document of ig-ss_x-road_v6_security_server_installation_guide_2.2.1_Y-745-8.docx successfully. So I download the global configuration anchor file of develop environment and import to the xroad.
On the Configuration menu, I select Security Server Clients,Click Add Client. In the window that opens, enter the client's information manually, it conforms that The person/organisation ' COM: memtest' is not registered as X-Road member. the name of list show that <Client not found in global configuration>,and only have 'Detail' button authority,don't have 'Service clients' ‘Service' 'Internal Server' button authority.How can I register the client in the global configuration? and How can I have all the button authority in the list?
thank you

**Comment by petkivim** [comment]
Hi,

If you want join the Finnish development environment you should follow these instructions:

https://esuomi.fi/palveluntarjoajille/palveluvayla/kehitys-ja-testiymparisto/kehitysymparisto/liittymisohje-kehitysymparisto/

Please note that Finnish development environment is for Finnish organizations and developers only.

Thanks,
Petteri

**Comment by hanhaka** [comment]
Issue resolved, closing it.
